a=int(input("ENTER A AMOUNT:"))
b=a//2000
c=a//500
d=a//100
x="NUMBER OF 2000 NOTES WITHDRAW IN GIVEN AMMOUNT IS %d"%(b)
y="NUMBER OF 500 NOTES WITHDRAW IN GIVEN AMMOUNT IS %d"%(c)
z="NUMBER OF 100 NOTES WITHDRAW IN GIVEN AMMOUNT IS %d"%(d)
print(x)
print(y)
print(z)
